# Logging configuration
logging:
  version: 1
  formatters:
    ETLPipeline:
      format: "ETL Transformer - %(asctime)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: ETLPipeline
      level: DEBUG
  root:
    level: DEBUG
    handlers: [ console ]